# Generated by Django 5.2.14 on 2026-06-09 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_perfil_id'),
        ('core', '0002_alter_perfil_id_historial_favorito'),
    ]

    operations = [
    ]
