# Generated by Django 5.2.14 on 2026-05-16 19:56

import django.db.models.deletion
import locations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text="Identificador único en URLs (ej. 'escom-ipn')", unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text="Código corto del edificio (ej. 'A', '1', 'H')", max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('pisos', models.PositiveSmallIntegerField(default=1)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to='locations.campus')),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
                'ordering': ['campus', 'codigo'],
                'unique_together': {('campus', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('aula', 'Aula'), ('laboratorio', 'Laboratorio'), ('oficina', 'Oficina'), ('servicio', 'Servicio (cafetería, biblioteca, etc.)')], max_length=20)),
                ('codigo', models.SlugField(help_text="Identificador único usado en URLs y QRs (ej. 'escom-entrada-principal')", max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('piso', models.IntegerField(default=0, help_text='0 para planta baja o exterior')),
                ('capacidad', models.PositiveIntegerField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, help_text="Ej. 'L-V 7:00-21:00 · S 8:00-14:00'", max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='locations.campus')),
                ('edificio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones', to='locations.edificio')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['campus', 'tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CodigoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to=locations.models.qr_upload_path)),
                ('url_destino', models.URLField(help_text='URL que se codifica dentro del QR', max_length=500)),
                ('escaneos', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultimo_escaneo', models.DateTimeField(blank=True, null=True)),
                ('ubicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_qr', to='locations.ubicacion')),
            ],
            options={
                'verbose_name': 'Código QR',
                'verbose_name_plural': 'Códigos QR',
                'ordering': ['-creado'],
            },
        ),
    ]
