# Generated by Django 5.2.14 on 2026-05-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='latitud',
            field=models.FloatField(blank=True, help_text='Latitud geográfica del edificio (ej. 19.504505)', null=True),
        ),
        migrations.AddField(
            model_name='edificio',
            name='longitud',
            field=models.FloatField(blank=True, help_text='Longitud geográfica del edificio (ej. -99.146911)', null=True),
        ),
    ]
