# Generated by Django 5.2.14 on 2026-05-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_edificio_latitud_edificio_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('aula', 'Aula'), ('laboratorio', 'Laboratorio'), ('oficina', 'Oficina'), ('servicio', 'Servicio (cafetería, biblioteca, etc.)'), ('baño', 'Baño')], max_length=20),
        ),
    ]
