# Generated by Django 5.2.14 on 2026-05-30 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_ubicacion_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edificio',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='longitud',
        ),
        migrations.AlterField(
            model_name='campus',
            name='codigo',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='codigoqr',
            name='url_destino',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='codigo',
            field=models.SlugField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='horario',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='piso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('aula', 'Aula'), ('laboratorio', 'Laboratorio'), ('oficina', 'Oficina'), ('servicio', 'Servicio (cafetería, biblioteca, etc.)'), ('bano', 'Baño')], max_length=20),
        ),
        migrations.CreateModel(
            name='NodoGrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text="Identificador único del nodo (ej. 'escom-plaza-central')", max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada del campus'), ('pasillo', 'Pasillo'), ('cruce', 'Cruce'), ('plaza', 'Plaza / Explanada'), ('edificio', 'Entrada a edificio'), ('escalera', 'Escalera')], default='pasillo', max_length=20)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos', to='locations.campus')),
                ('ubicacion', models.OneToOneField(blank=True, help_text='Vincula este nodo a una Ubicación (entrada, edificio) para que las rutas la usen automáticamente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodo_grafo', to='locations.ubicacion')),
            ],
            options={
                'verbose_name': 'Nodo del grafo',
                'verbose_name_plural': 'Nodos del grafo',
                'ordering': ['campus', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='AristaGrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_m', models.DecimalField(decimal_places=2, help_text='Distancia en metros (se calcula automática al guardar)', max_digits=8)),
                ('tipo', models.CharField(choices=[('pasillo', 'Pasillo cerrado'), ('sendero', 'Sendero exterior'), ('escalera', 'Escalera'), ('plaza', 'Cruce de plaza')], default='sendero', max_length=20)),
                ('accesible', models.BooleanField(default=True, help_text='¿Es accesible para silla de ruedas? (sin escaleras)')),
                ('bidireccional', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aristas_entrada', to='locations.nodografo')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aristas_salida', to='locations.nodografo')),
            ],
            options={
                'verbose_name': 'Arista del grafo',
                'verbose_name_plural': 'Aristas del grafo',
                'ordering': ['origen', 'destino'],
                'unique_together': {('origen', 'destino')},
            },
        ),
    ]
